/* Paste the generated code from the Test form here (always replace the entire code block) */

/*  vvvvvvvvvvvvvvvvvvvvvv  CODE GOES HERE vvvvvvvvvvvvvvvvvvvvvvvvvvvv   */

localStorage.Test1 = JSON.stringify({"questions":[{"q":"1 + 1 is some long text whatever etc etc etc etc etc, more, 1 + 1 is some long text whatever etc etc etc etc etc, more1 + 1 is some long text whatever etc etc etc etc etc, more, 1 + 1 is some long text whatever etc etc etc etc etc, more","a":"2"},{"q":"3 + 6 is","a":"9"},{"q":"4 x 2 is","a":"8"}],"ric":"T"});var test_1 = JSON.parse(localStorage.Test1);localStorage.Test2 = JSON.stringify({"questions":[{"q":"1 + 1 is some long text whatever etc etc etc etc etc, more, 1 + 1 is some long text whatever etc etc etc etc etc, more1 + 1 is some long text whatever etc etc etc etc etc, more, 1 + 1 is some long text whatever etc etc etc etc etc, more","a":"T"},{"q":"Nando's sell sushi","a":"F"},{"q":"Brazil won the FIFA World Cup 2014","a":"F"}],"ric":""});var test_2 = JSON.parse(localStorage.Test2);localStorage.Test3 = JSON.stringify({"questions":[{"q":"1 + 1 is some long text whatever etc etc","id":"T3Q0","a":"T3O2"},{"q":"Table Mountain is in","id":"T3Q1","a":"T3O1"},{"q":"The sun is","id":"T3Q2","a":"T3O0"}],"ric":"","options":[{"o":"1 + 1 is some long text whatever etc etc etc etc etc, more, 1 + 1 is some long text whatever etc etc etc etc etc, more1 + 1 is some long text whatever etc etc etc etc etc, more, 1 + 1 is some long text whatever etc etc etc etc etc, more"},{"o":"Cape Town"},{"o":"Pretoria"}]});var test_3 = JSON.parse(localStorage.Test3);localStorage.Test4 = JSON.stringify({"questions":[{"q":"1 + 1 is some long text whatever etc etc etc etc etc, more, 1 + 1 is some long text whatever etc etc etc etc etc, more1 + 1 is some long text whatever etc etc etc etc etc, more, 1 + 1 is some long text whatever etc etc etc etc etc, more","id":"T4Q0","options":[{"o":"o1 long text whatever etc etc etc etc etc, more, 1 + 1 is s","option_id":"T4Q0O0","correct":"T"},{"o":"o3","option_id":"T4Q0O1","correct":"F"}]},{"q":"Q2","id":"T4Q1","options":[{"o":"o1","option_id":"T4Q1O0","correct":"T"},{"o":"o2 long text whatever etc etc etc etc etc, more, 1 + 1 is s","option_id":"T4Q1O1","correct":"F"}]},{"q":"Q3","id":"T4Q2","options":[{"o":"o1","option_id":"T4Q2O0","correct":"F"},{"o":"o2","option_id":"T4Q2O1","correct":"F"},{"o":"o3","option_id":"T4Q2O2","correct":"F"},{"o":"o4","option_id":"T4Q2O3","correct":"T"}]}],"ric":"T","options":[]});var test_4 = JSON.parse(localStorage.Test4);

/*  ^^^^^^^^^^^^^^^^^^^^^  CODE GOES HERE ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   */



